# Generated by Django 3.2.15 on 2022-09-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20220831_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsinfo',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
