# Generated by Django 3.2.15 on 2022-09-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20220902_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsinfo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
